version: '3.8'

services:
    AuthServer:
        image: mysql
        container_name: MikyAuthServer
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        ports:
            - 3366:3306
        environment: 
        # MODIFY PASSWORDS BEFORE YOU RUN DOCKER COMPOSE!!!
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: authServerDb
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        # /////////////////////////
        volumes: 
            - ./Init:/docker-entrypoint-initdb.d

    AuthServerAdminer:
        image: adminer
        container_name: MikyAuthServerAdminer
        restart: unless-stopped
        ports: 
            - 8080:8080
